version: '3.8'

services:
  kotaemon:
    image: ghcr.io/cinnamon/kotaemon:main-full
    container_name: kotaemon
    ports:
      - "8000:7860"
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    volumes:
      - ./ktem_app_data:/app/ktem_app_data
      - ./.env:/app/.env
    restart: unless-stopped
